### PR TITLE
FIX Allow running on local machines without global PHPUnit install

### PR DESCRIPTION
**Pull request by SilbinaryWolf**
FIX, Errors occurred when running tests locally (couldn't find PHPUnit files) and 1 missing abstract method addRiskyTest.

### CODE REVIEW

**Comment by nyeholt** [comment]
Doesn't the base project require-dev of phpunit make sure these are available?

**Comment by SilbinaryWolf** [comment]
Yeah, but AFAIK release doesn't use the composer included version of PHPUnit.
In anycase, I don't know why "require_once" statements are there, I'm just avoiding including them if they're not needed.

**Comment by SilbinaryWolf** [comment]
@nyeholt ?

**Comment by nyeholt** [comment]
> Errors occurred when running tests locally

> AFAIK release doesn't use the composer included version of PHPUnit

Where are you actually getting the failure? The build process excludes the test-assist folder before deployment in a release environment, so the second point shouldn't be an issue. The first _should_ have phpunit available as a dev-dependency via composer; not to say that removing this PR shouldn't happen, but I want to know what's actually failing because it might need a broader fix.

**Comment by SilbinaryWolf** [comment]
I can't actually reproduce this anymore.
If I remember/re-hit this, I'll let you know.

Tried:

- Running dev/task via ci_tests in Phing
- Runnng dev/task via web

**Comment by nyeholt** [comment]
To add to this - had a possibly similar issue

```
PHP Warning:  require_once(PHPUnit/Framework/TestListener.php): failed to open stream: No such file or directory in /var/www/dynamic/hoho/hoho-mpw/framework/dev/SapphireTestReporter.php on line 4

Warning: require_once(PHPUnit/Framework/TestListener.php): failed to open stream: No such file or directory in /var/www/dynamic/hoho/hoho-mpw/framework/dev/SapphireTestReporter.php on line 4
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework/TestListener.php' (include_path='/var/www/dynamic/hoho/hoho-mpw/vendor/phpunit/phpunit-selenium:.:/var/www/dynamic/hoho/hoho-mpw/framework:/var/www/dynamic/hoho/hoho-mpw/framework/parsers:/var/www/dynamic/hoho/hoho-mpw/framework/thirdparty:.:/usr/share/php:/usr/share/pear:/var/www/dynamic/hoho/hoho-mpw/vendor/phpunit/phpunit/src') in /var/www/dynamic/hoho/hoho-mpw/framework/dev/SapphireTestReporter.php on line 4

```

The interesting thing was that adding a get_declared_classes call immediately before the class_exists check in SapphireTestReporter would show the class was _already declared_. Removing the commented out lines would mean that things would execute totally fine too and not need the two files included. So I'm at a loss as to why / what the class_exists call ends up doing to cause grief here.

**Pull request merged**
